version: "3.0"

services:
  backend-mysql-server:
    build:
      context: ./
      dockerfile: ./Docker/backend-mysql-server/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DEFAULT_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - emart-database:/var/lib/mysql
  backend-node-server:
    depends_on:
      - backend-mysql-server
    build:
      context: ./
      dockerfile: ./Docker/backend-node-server/Dockerfile
    restart: unless-stopped
    ports:
      - $BACKEND_NODE_SERVER_LOCAL_PORT:$BACKEND_NODE_SERVER_DOCKER_PORT
    environment:
      - NODE_ENV=$BACKEND_NODE_ENV
      - CORS_ORIGIN=$BACKEND_CORS_ORIGIN
      - NODEMAILER_USER=$BACKEND_NODEMAILER_USER
      - NODEMAILER_APP_PASSWORD=$BACKEND_NODEMAILER_APP_PASSWORD
      - NODEMAILER_DOMAIN=$BACKEND_NODEMAILER_DOMAIN
      - NEWSLETTER_VALIDATION_TOKEN_SECRET_KEY=$BACKED_NEWSLETTER_VALIDATION_TOKEN_SECRET_KEY
      - DATABASE_HOST=backend-mysql-server
      - DATABASE_USER=root
      - DATABASE_PASSWORD=$MYSQL_ROOT_PASSWORD
      - DATABASE_NAME=$MYSQL_DEFAULT_DATABASE
      - PORT=$BACKEND_NODE_SERVER_DOCKER_PORT
    volumes:
      - emart-upload:/myapp/upload
  frontend-node-server:
    depends_on:
      - backend-node-server
    build:
      context: ./
      dockerfile: ./Docker/frontend-node-server/Dockerfile
      args: 
      - NODE_ENV=$FRONTEND_NODE_ENV
      - API_URL=$FRONTEND_API_URL
      - UPLOAD_URL=$FRONTEND_UPLOAD_URL
      - PORT=$FRONTEND_NODE_SERVER_DOCKER_PORT
    restart: unless-stopped
    ports:
    - $FRONTEND_NODE_SERVER_LOCAL_PORT:$FRONTEND_NODE_SERVER_DOCKER_PORT
  nginx-server:
    depends_on:
      - backend-mysql-server
      - backend-node-server
      - frontend-node-server
    build:
      context: ./
      dockerfile: ./Docker/nginx-server/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=$NGINX_DOMAIN
      - API_DOMAIN=$NGINX_API_DOMAIN
      - UPLOAD_DOMAIN=$NGINX_UPLOAD_DOMAIN
      - BACKEND_NODE_SERVER_DOCKER_PORT=$BACKEND_NODE_SERVER_DOCKER_PORT
      - FRONTEND_NODE_SERVER_DOCKER_PORT=$FRONTEND_NODE_SERVER_DOCKER_PORT
      - NGINX_CERTIFICATE_FILE_NAME=$NGINX_CERTIFICATE_FILE_NAME
      - NGINX_CERTIFICATE_KEY_FILE_NAME=$NGINX_CERTIFICATE_KEY_FILE_NAME
    volumes:
      - emart-upload:/myapp/upload
volumes: 
  emart-database:
  emart-upload: